name: WebGL Build and Deploy

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2022.3.14f1
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build WebGL
        run: |
          mkdir -p Builds/WebGL
          /opt/Unity/Editor/Unity -quit -batchmode -projectPath . -buildTarget WebGL -executeMethod BuildScript.BuildWebGL

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Builds/WebGL
